name: Build V2Ray rules dat files

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * FRI"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # --------------------------------------------------------------
      # 1. Generate timestamp tag (WIB +7) + environment variables
      # --------------------------------------------------------------
      - name: Generate Release Tag (WIB +7)
        id: vars
        run: |
          # Use WIB / Asia-Jakarta timezone
          export TZ="Asia/Jakarta"

          # Custom format: HHMMDDMMYYYY
          TAG_NAME=$(date +%H%M%d%m%Y)
          RELEASE_NAME="Released on $TAG_NAME (WIB)"

          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV

          # Rule URLs
          echo "HAGEZI_PRO_FULL=https://codeberg.org/hagezi/mirror2/raw/branch/main/dns-blocklists/dnsmasq/pro.txt" >> $GITHUB_ENV
          echo "HAGEZI_NSFW=https://codeberg.org/hagezi/mirror2/raw/branch/main/dns-blocklists/dnsmasq/nsfw.txt" >> $GITHUB_ENV
          echo "DOH_DNS=https://raw.githubusercontent.com/dibdot/DoH-IP-blocklists/master/doh-domains.txt" >> $GITHUB_ENV
          echo "RULE_ADS=https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.txt" >> $GITHUB_ENV
          echo "RULE_ADS_EXTENDED=https://raw.githubusercontent.com/rfxcll/v2ray-rules-dat/rule/rule_ads.txt" >> $GITHUB_ENV
          echo "RULE_GAME=https://raw.githubusercontent.com/rfxcll/v2ray-rules-dat/rule/rule_gaming.txt" >> $GITHUB_ENV
          echo "RULE_INDO=https://raw.githubusercontent.com/rfxcll/v2ray-rules-dat/rule/rule_indo.txt" >> $GITHUB_ENV
          echo "RULE_PS=https://raw.githubusercontent.com/rfxcll/v2ray-rules-dat/rule/rule_playstore.txt" >> $GITHUB_ENV
          echo "RULE_SOSMED=https://raw.githubusercontent.com/rfxcll/v2ray-rules-dat/rule/rule_sosmed.txt" >> $GITHUB_ENV
          echo "RULE_STREAMING=https://raw.githubusercontent.com/rfxcll/v2ray-rules-dat/rule/rule_streaming.txt" >> $GITHUB_ENV
          echo "RULE_UMUM=https://raw.githubusercontent.com/rfxcll/v2ray-rules-dat/rule/rule_umum.txt" >> $GITHUB_ENV
          echo "RULE_IPCHECK=https://raw.githubusercontent.com/rfxcll/v2ray-rules-dat/rule/rule_ipcheck.txt" >> $GITHUB_ENV
          echo "RULE_VIDCONFERENCE=https://raw.githubusercontent.com/rfxcll/v2ray-rules-dat/rule/rule_videoconference.txt" >> $GITHUB_ENV
          echo "URLTEST=https://raw.githubusercontent.com/rfxcll/v2ray-rules-dat/rule/urltest.txt" >> $GITHUB_ENV
          echo "RULE_SPEEDTEST=https://raw.githubusercontent.com/rfxcll/v2ray-rules-dat/rule/rule_speedtest.txt" >> $GITHUB_ENV
          echo "MALICIOUS_HOST=https://raw.githubusercontent.com/elliotwutingfeng/Inversion-DNSBL-Blocklists/main/Google_hostnames_light.txt" >> $GITHUB_ENV
          echo "RULE_BANK_ID=https://raw.githubusercontent.com/rfxcll/v2ray-rules-dat/rule/rule_bank-id.txt" >> $GITHUB_ENV
          echo "RULE_ECOMMERCE=https://raw.githubusercontent.com/rfxcll/v2ray-rules-dat/rule/rule_ecommerce.txt" >> $GITHUB_ENV

      # --------------------------------------------------------------
      # 2. Checkout source repositories
      # --------------------------------------------------------------
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/checkout@v4
        with:
          repository: Loyalsoldier/domain-list-custom
          path: custom

      - uses: actions/checkout@v4
        with:
          repository: v2fly/domain-list-community
          path: community

      # --------------------------------------------------------------
      # 3. Setup Go
      # --------------------------------------------------------------
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./custom/go.mod
          cache-dependency-path: ./custom/go.sum

      # --------------------------------------------------------------
      # 4. Download geoip.dat
      # --------------------------------------------------------------
      - name: Download geoip.dat
        run: |
          wget https://github.com/malikshi/geoip/raw/release/geoip.dat
          wget https://github.com/malikshi/geoip/raw/release/geoip.dat.sha256sum

      # --------------------------------------------------------------
      # 5. Generate custom lists
      # --------------------------------------------------------------
      - name: Create Custom Lists
        run: |
          curl -sSL "$HAGEZI_PRO_FULL"  | perl -ne '/^local=\/([^\/]+)\// && print "$1\n"' > community/data/hagezi-pro-full
          curl -sSL "$RULE_ADS" | awk '/0.0.0.0/{print $2}' > community/data/rule-ads
          curl -sSL "$RULE_ADS_EXTENDED" >> community/data/rule-ads
          curl -sSL "$HAGEZI_NSFW"  | perl -ne '/^local=\/([^\/]+)\// && print "$1\n"' > community/data/hagezi-nsfw

          curl -sSo community/data/rule-doh "$DOH_DNS"
          curl -sSo community/data/rule-gaming "$RULE_GAME"
          curl -sSo community/data/rule-indo "$RULE_INDO"
          curl -sSo community/data/rule-playstore "$RULE_PS"
          curl -sSo community/data/rule-sosmed "$RULE_SOSMED"
          curl -sSo community/data/rule-streaming "$RULE_STREAMING"
          curl -sSo community/data/rule-umum "$RULE_UMUM"
          curl -sSo community/data/rule-speedtest "$RULE_SPEEDTEST"
          curl -sSo community/data/rule-ipcheck "$RULE_IPCHECK"
          curl -sSo community/data/videoconference "$RULE_VIDCONFERENCE"
          curl -sSo community/data/urltest "$URLTEST"
          curl -sSo community/data/rule-malicious "$MALICIOUS_HOST"
          curl -sSo community/data/bank-id "$RULE_BANK_ID"
          curl -sSo community/data/ecommerce-id "$RULE_ECOMMERCE"

      # Filter d3ward list
      - name: Filter d3ward list
        run: |
          python <<EOF
          import requests
          url = "https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.txt"
          data = requests.get(url).text
          with open("community/data/d3ward", "w") as f:
              for line in data.split("\n"):
                  if line.startswith("0.0.0.0 "):
                      f.write(line.replace("0.0.0.0 ", "") + "\n")
          EOF

      # --------------------------------------------------------------
      # 6. Build geosite.dat
      # --------------------------------------------------------------
      - name: Build geosite
        run: |
          cd custom
          go run ./ --datapath=../community/data

      # --------------------------------------------------------------
      # 7. Package files
      # --------------------------------------------------------------
      - name: Package files
        run: |
          mkdir -p publish
          install -Dp ./geoip.dat ./publish/GeoIP.dat
          install -Dp ./geoip.dat.sha256sum ./publish/GeoIP.dat.sha256sum
          install -Dp ./custom/publish/geosite.dat ./publish/GeoSite.dat

          cd publish
          zip Geo-files.zip GeoIP.dat GeoSite.dat
          sha256sum GeoSite.dat > GeoSite.dat.sha256sum
          sha256sum Geo-files.zip > Geo-files.zip.sha256sum

      # --------------------------------------------------------------
      # 8. Convert to Sing-Box DB
      # --------------------------------------------------------------
      - name: Convert to Sing-Box DB
        run: |
          wget https://github.com/malikshi/Notes/releases/download/v2box/v2box
          chmod +x v2box

          ./v2box migrate geoip -i publish/GeoIP.dat -o publish/GeoIP.db
          ./v2box migrate geosite -i publish/GeoSite.dat -o publish/GeoSite.db

          cd publish
          sha256sum GeoSite.db > GeoSite.db.sha256sum
          sha256sum GeoIP.db > GeoIP.db.sha256sum

      # --------------------------------------------------------------
      # 9. Create & push tag (important)
      # --------------------------------------------------------------
      - name: Push tag for release
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"

      # --------------------------------------------------------------
      # 10. Create GitHub Release + upload assets
      # --------------------------------------------------------------
      - name: Create GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: ${{ env.RELEASE_NAME }}
          tag: ${{ env.TAG_NAME }}
          file: ./publish/*
          file_glob: true

      # --------------------------------------------------------------
      # 11. Push files to release branch
      # --------------------------------------------------------------
      - name: Push files to release branch
        run: |
          cd publish
          git init
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release

      # --------------------------------------------------------------
      # 12. Purge jsDelivr CDN cache
      # --------------------------------------------------------------
      - name: Purge jsDelivr CDN
        run: |
          cd publish
          for f in *; do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/$f"
          done

      # --------------------------------------------------------------
      # 13. Delete old releases
      # --------------------------------------------------------------
      - name: Delete old releases
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          repo: ${{ github.repository }}
          keep_latest: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
